services:
  tic-tac-toe:
    image: ${DOCKER_REGISTRY:-ghcr.io}/mark3835/202510_lab1
    container_name: tic-tac-toe-game
    user: "1000:1000"  # 添加使用者權限設定
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=Asia/Taipei
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "app.description=Tic Tac Toe Game"
      - "app.version=latest"